FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04


# 1. System dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.10 python3.10-venv python3-pip \
    libglib2.0-0 libsm6 libxrender1 libxext6 libgl1 \
    git wget curl unzip ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# 2. Set Python 3.10 as default
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1

# 3. Create app directory
WORKDIR /app


# 4. Copy requirements
COPY requirements.txt .


# 5. Install Python packages
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy the application code
COPY . /app

# Default command
CMD ["python", "main.py"]