FROM --platform=linux/arm64 nvcr.io/nvidia/l4t-base:r32.7.1

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1


# # Jo te nav kkads public key prieks taa public repo
# RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 16FAAD7AF99A65E2

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip python3-opencv python3-dev \
    libgl1 libx11-6 libglib2.0-0 libfreetype6-dev \
    build-essential pkg-config wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
RUN ln -sf /usr/bin/python3 /usr/bin/python

# Install Python dependencies
RUN python3 -m pip install protobuf==3.19.6

# Install ONNX Runtime GPU for Jetson (v1.10.0, Python 3.6 required by L4T r32.7.1)
RUN python3 -m pip install --upgrade pip \
    && wget https://nvidia.box.com/shared/static/jy7nqva7l88mq9i8bw3g3sklzf4kccn2.whl -O onnxruntime_gpu-1.10.0-cp36-cp36m-linux_aarch64.whl \
    && python3 -m pip install onnxruntime_gpu-1.10.0-cp36-cp36m-linux_aarch64.whl \
    && rm onnxruntime_gpu-1.10.0-cp36-cp36m-linux_aarch64.whl

# Add other required Python dependencies
COPY requirements.txt .
RUN python3 -m pip install -r requirements.txt \
    && python3 -m pip install onnx==1.11.0 \
    && rm -rf ~/.cache/pip

COPY . /app
WORKDIR /app

CMD ["python3", "main.py"]